### PR TITLE
Allow client to always use native setTimeout function. 

### PR DESCRIPTION
**Pull request by vartan**
This allows socket.io client to be used in testing infrastructure (such as Karma) where the clock may be mocked.

*Note*: the `socket.io.js` file is the generated output of `make socket.io.js`, and should not be manually modified.

### The kind of change this PR does introduce

* [ ] a bug fix
* [x] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour
If the test infrastructure socket attempts to reconnect while a mock clock is installed, it will never reconnect. This happens when Karma is configured to use socket.io.

### New behaviour
If the socket attempts to reconnect while the mock clock is installed and `useNativeSetTimeout` is set, then it will not use the mocked clock and will reconnect normally

### CODE REVIEW

**Comment by darrachequesne** [comment]
@vartan thanks for the pull request! There are several usages of `setTimeout` in `engine.io-client`, do you think we should add the option there too?

**Comment by vartan** [comment]
Yeah, that seems like the right thing to do, I didn't realize that was split out of socket.io-client. Is there somewhere central you recommend I implement this? I'll take a look tomorrow.

**Comment by vartan** [comment]
I sent a PR to engine.io-client, I'll refactor this one once that is submitted. thanks again.

**Comment by vartan** [comment]
Hi Damien, I've updated this PR to use the changes in https://github.com/socketio/engine.io-client/pull/672

**Comment by vartan** [comment]
I wonder if we should also bump up the version of engine.io-client to ensure the change is in

**Comment by vartan** [comment]
friendly ping

**Comment by darrachequesne** [comment]
Merged as https://github.com/socketio/socket.io-client/commit/4e1b65699d9967a7bb409bdc89c894c62562771b. I'll keep you updated once it is released.

**Comment by darrachequesne** [comment]
This was included in latest release: https://github.com/socketio/socket.io-client/releases/tag/4.2.0

Again, thanks for your work on this.

**Pull request closed without merging**
