### PR TITLE
Added bower.json configuration file

### PR DESCRIPTION
**Pull request by MJBGO**
Added bower.json configuration file. Helps using the lib with gulp or grunt.

### CODE REVIEW

**Comment by richburdon** [comment]
Is this package registered with bower?

I see several people forking the project in order to register what seem to be unofficial versions:
https://github.com/Alexandre-io/socket.io-client

**Comment by MJBGO** [comment]
No it's not, that's why I added this file but no answer ^^^'

**Comment by nuclearace** [comment]
Doesn't bower need to know what dependencies are needed? Also the version needs to be updated

**Comment by nkzawa** [comment]
Bower would not be supported. Please see https://github.com/socketio/engine.io-client/issues/289#issuecomment-40621081 for the reason.

**Comment by gaelduplessix** [comment]
Bower should definitely be supported. I agree it's a shame that as library authors you have to maintain several different manifest files but that's the state of front-end package management today.
Most libraries authors have accepted that and deal with it now, please integrate it too.
Lots of webapps build toolchains are based on bower.json manifests, without it they have to be updated just to support this single library, or use a fork...

**Pull request closed without merging**
