### PR TITLE
add support for per transport options

### PR DESCRIPTION
**Pull request by liorsion**
sometimes we need different transports to go to different destinations.

For example, when doing ELB load balancing, ELB can't do both websockets (TCP) and HTTP affinity (which is needed for polling) unless we use different ports.

With this simple solution socket.io can now easily work with ELB.

### CODE REVIEW

**Comment by nkzawa** [comment]
Basically, a client connection has to go to a same destination to keep session even after upgrading transports.
I think you can explicitly set different url and transports setting like the followings If you'd like to make transports go different destinations.

```js
io('http://foo', { transports: ['websocket'] });
io('http://bar', { transports: ['polling'] })
```

Feel free to reopen if I'm missing something.

**Comment by liorsion** [comment]
@nkzawa this is actually needed like this. I will try to summarize it in short and if not clear enough post a blog post - because this is long.. sorry.

the objective is to work with Amazon ELB (load balancer). This ELB has a weird twist: it can EITHER do session stickiness on the HTTP level (which we need for xhr) OR support TCP connection (which we need for websockets). Look around the internet - there's no easy solution for using ELB and socket.io

Using this change, we can configure elb to support HTTP session stickiness on one port and TCP on the other while direction to the same server (or cluster) in the background - and so in effect get what you  were writing about.

I know if we would have controlled the entire stack this solution was actually supposed to be in ELB and not here, and there's some code smell due to that, however, Amazon and ELB are very wildly supported and good luck moving them along.. :(

**Comment by nkzawa** [comment]
> Using this change, we can configure elb to support HTTP session stickiness on one port and TCP on the other while direction to the same server (or cluster) in the background - and so in effect get what you were writing about.

Sounds reasonable. Any thoughts, @rauchg ?

**Comment by rauchg** [comment]
Needs documenting. Sounds good to me.

**Comment by liorsion** [comment]
can we use what I wrote? I will have a blog post by eow I hope..

**Comment by liorsion** [comment]
@rauchg how's this? http://bringg.com/technical/socket-io/

**Comment by rauchg** [comment]
@liorsion looks really good! Why not:

```js
io({ 
  transportOptions: {
    polling: { /* opts */ },
    websocket: { /* opts */ }
  }
});
```

seems clearer, and doesn't imply that you have to list all the transports you want to support.

**Comment by liorsion** [comment]
@rauchg because you need to separately define transports and their options, which might cause mistakes (you defined websockets options but not the transport, etc). Making one call to define both seems to make more sense.

I guess the disadvantage is that you need to define your transports and not use the default order etc, however, someone doing this type of integration probably know what they are doing..

**Comment by rauchg** [comment]
@liorsion I'd like to go with `transportOptions`, since it would allow you to change the options for a single transport without redefining everything, or knowing about other transports that are user-defined.

**Comment by nkzawa** [comment]
It looks `socket.io.js` was modified in this PR. but that should be done in `engine.io-client` instead. `socket.io.js` is just a generated file.

**Comment by darrachequesne** [comment]
The discussion continues here: https://github.com/socketio/engine.io-client/pull/480

**Pull request closed without merging**
