### PR TITLE
When emitting from timeout() prepend timeout error

### PR DESCRIPTION
**Pull request by engina**
Attempts to fix https://github.com/socketio/socket.io-client/issues/1555

### The kind of change this PR does introduce

* [x] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [x] a code change that improves performance
* [ ] other

### CODE REVIEW

**Comment by engina** [comment]
I noticed an issue https://github.com/engina/socket.io-client/issues/1

Also fixed with the help of systemdefault from irg.libera.chat/typescript

**Comment by darrachequesne** [comment]
Merged as https://github.com/socketio/socket.io-client/commit/33e417258c9a5697e001163971ae87821e9c097f. Thanks a lot :heart:

**Comment by engina** [comment]
Please see https://github.com/engina/socket.io-client/issues/1

Merged solution is suboptimal -- it loses argument labels. Perfect typing solution is proposed in the link and forked repo -- but it requires a newer tsc it seems. I tried to clean up a pull request for that too, but I got lost in build system intricacies and gave up.

**Comment by darrachequesne** [comment]
@engina arf, it seems you are right:

Screenshot from 2023-01-17 09-03-42

I tried to fix the behavior with an untyped socket (which defaults to [`DefaultEventsMap`](https://github.com/socketio/socket.io-client/blob/33e417258c9a5697e001163971ae87821e9c097f/lib/socket.ts#L118)), and lost the labels along the way...

Screenshot from 2023-01-17 09-06-12

If you have any pointer :innocent:

**Comment by engina** [comment]
@darrachequesne This gives perfect typings: https://github.com/engina/socket.io-client/blob/c8ff4b6351ec575ecf3dbcd4c487aa3c5283795e/lib/socket.ts

But your build system (tsd?) doesn't like it. So I started upgrading tsc (wrongfully i guess) but then things started to get hairy. And at this point I was exhausted :)

I would like to look at that again but very busy with work now.

My suggestion:
1. You could try merging JUST the socket.ts I linked above.
2. Verify typings work. (They worked perfectly in VS code for me)
3. Make it build and pass the tests

**Pull request closed without merging**
