### PR TITLE
Fix of reconnection stopping during disconnect

### PR DESCRIPTION
**Pull request by Xubor**
Proposed solution to #852

### CODE REVIEW

**Comment by nkzawa** [comment]
Thanks for your PR! Can you add tests if possible?

**Comment by fourpixels** [comment]
Am I missing something, or this is **STILL** not released?!?

Commits on Jun 18, 2015 - come on!

**Comment by nkzawa** [comment]
I could reproduce #849, but could not #852. How can I do that @Xubor ?

**Comment by nkzawa** [comment]
Merged since this fixes #849. I couldn't reproduce #852 .

**Pull request merged**
