### PR TITLE
Add browserfy option "browser".

### PR DESCRIPTION
**Pull request by whitecolor**
Just to support correct loading.

### CODE REVIEW

**Comment by nkzawa** [comment]
Thanks but `socket.io.js` is not the entry point, but the built file for browser.

**Comment by whitecolor** [comment]
You mean not entry point for browserfy?

**Comment by nkzawa** [comment]
yep, it's not entry point for browserify. The entry point is the same with node.js. so I think we'd not need to set `browser` field.

**Comment by whitecolor** [comment]
Ok, jspm is set right.

**Pull request closed without merging**
