### PR TITLE
Fixes #1014 (EIO socket leak) and refactors Manager and Socket

### LINKED ISSUE #1014: [Bug] Manager leaks an EIO socket when disconnect is called right before connecting again
### server.js:

``` js
var io = require('socket.io')(1337);

io.of('/asd');
io.of('/foo');
```
### client.js:

``` js
var io = require('./');
var manager = io.Manager('http://localhost:1337', { transports: ['websocket'] });

var fooSocket = manager.socket('/foo');
fooSocket.on('connect', function() {
  // This disconnect should not break
  // the conection of the asdSocket.
  fooSocket.disconnect();

  var asdSocket = manager.socket('/asd');

  // Only fail if reconnect_attempt it emitted
  // even if the IEO Socket was successfully opened.
  manager.engine.on('open', function() {
    asdSocket.on('reconnect_attempt', function() {
      console.error('Why reconnect? This is a bug!');
    });
  })

  asdSocket.on('connect', function() {
    asdSocket.disconnect();
    console.error('Node.js should exit after all clients have disconnected');
  });
});
```
## Expected behavior

Node.js should exit after all clients have disconnected.
## Actual behavior

Node.js freezes for about a second (before it tries to reconnect) and then it stays open forever (doesn't exit).
## Workaround

I am aware that the proper way to do something like this is to first connect to the second namespace and then disconnect from the first namespace.

However I don't think something like this should leak an IEO socket.
## Setup
- OS: macOS Version 10.12
- browser: Node.js v4.6.1
- socket.io version: 1.5.0
### Other information

See [this commit](https://github.com/benjamin-albert/socket.io-client/commit/a4b80b2724c37a4bc5690ec54c157230e9f8bcf1) in my [fix_eio_leak branch](https://github.com/benjamin-albert/socket.io-client/tree/fix_eio_leak) which adds a failing test to  `test/connection.js`

Stay tuned for a pull request that fixes this bug.

### PR DESCRIPTION
**Pull request by benjamin-albert**
This pull request fixes #1014, and adds an initially failing test (which passes after fixing the bug).
## Why do we have this bug

Calling `Socket.disconnect()` will eventually call [.close()](https://github.com/socketio/engine.io-client/blob/618758543/lib/socket.js#L629) on the Engine.IO Socket.

The Engine.IO Socket's `.close()` method listens to the `drain` event (which is eventually emitted by the underlying transport) and only then emits the `close` event.

The [Manager listens to the engine's close event](https://github.com/socketio/socket.io-client/blob/4578f7ed3/lib/manager.js#L290) and calls [Manager.cleanup()](https://github.com/socketio/socket.io-client/blob/4578f7ed3/lib/manager.js#L446) which removes all listeners.

However if you call `Socket.disconnect()` and then connect to another namespace the engine's `close` event will be **emitted before the transport has opened**, but [Manager.cleanup()](https://github.com/socketio/socket.io-client/blob/4578f7ed3/lib/manager.js#L446) will remove all listeners, **including the `open` and `error` listeners on the new engine** (see [Manager.connect()](https://github.com/socketio/socket.io-client/blob/4578f7ed3/lib/manager.js#L220)).

This means that the underlying transport will successfully emit the `open` event but the Manager doesn't listen to it.

Because the Manager thinks that the transport did not open the manager will attempt to reconnect (after a small delay) without closing the open EIO socket.
## Solution

I fixed the bug by refactoring Manager and Socket to use an inversion of control version of `.on()` and `.removeListener()` (which is heavily influenced by [Backone.js's .listenTo()](http://backbonejs.org/#Events-listenTo)) to:
1. Allow removing all listeners bound on a **specific EIO Socket** by a specific Manager instance.
2. Implicitly bind `this` to Manager or Socket.

I also moved the `skipReconnect` flag to the EIO Socket which prevents [Manager.onclose](https://github.com/socketio/socket.io-client/blob/4578f7ed3/lib/manager.js#L491) from triggering a reconnect because the subsequent [Manager.open()](https://github.com/socketio/socket.io-client/blob/4578f7ed3/lib/manager.js#L217) call reset it to `false`.

### CODE REVIEW

**Comment by benjamin-albert** [comment]
It seems the [connection should fire reconnect_* events on socket](https://travis-ci.org/socketio/socket.io-client/jobs/170188900) test is timing out only on Node v6.9.1.

The same test passed without any problem in the [previous build](https://travis-ci.org/socketio/socket.io-client/jobs/170129191#L152) and the new commit I pushed does not change this test or the implementation.

When I:

    nvm install 6.9.1
    nvm use 6.9.1

I cannot reproduce this timeout locally.

It also seems that jobs will fail on:

```
restarting: <android 4.3 on Linux>
restarting: <android 4.3 on Linux>
restarting: <android 4.3 on Linux>
restarting: <android 4.3 on Linux>
restarting: <android 4.3 on Linux>

Error: Not running
    at Server.close (net.js:1237:11)
    at Object.shutdown (/home/travis/build/socketio/socket.io-client/node_modules/zuul/lib/setup.js:111:17)
    at finish_shutdown (/home/travis/build/socketio/socket.io-client/node_modules/zuul/lib/SauceBrowser.js:256:29)
    at Object.callback (/home/travis/build/socketio/socket.io-client/node_modules/zuul/lib/SauceBrowser.js:287:13)
    at cb (/home/travis/build/socketio/socket.io-client/node_modules/zuul/node_modules/wd/lib/webdriver.js:216:36)
    at null.<anonymous> (/home/travis/build/socketio/socket.io-client/node_modules/zuul/node_modules/wd/lib/callbacks.js:42:9)
    at cb (/home/travis/build/socketio/socket.io-client/node_modules/zuul/node_modules/wd/lib/webdriver.js:160:22)
    at /home/travis/build/socketio/socket.io-client/node_modules/zuul/node_modules/wd/lib/webdriver.js:174:5
    at Request._callback (/home/travis/build/socketio/socket.io-client/node_modules/zuul/node_modules/wd/lib/http-utils.js:85:7)
    at Request.self.callback (/home/travis/build/socketio/socket.io-client/node_modules/zuul/node_modules/wd/node_modules/request/request.js:364:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/travis/build/socketio/socket.io-client/node_modules/zuul/node_modules/wd/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/travis/build/socketio/socket.io-client/node_modules/zuul/node_modules/wd/node_modules/request/request.js:1266:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
```

@darrachequesne  I noticed this failure on pretty much all other pull requests. What does this mean?

* Is my new test failing?
* Is some other test failing?

**Comment by benjamin-albert** [comment]
Can anyone explain to me how a falling build vanished and was replaced with a passing build?

**Comment by darrachequesne** [comment]
Hi! Sorry for the delay, I'll try to review that when I'll have some time.

(regarding the failing build, I restarted it manually :angel:)

**Comment by knoxcard** [comment]
Any updates on this?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Pull request closed without merging**
