### PR TITLE
Update engine.io to include security patch

### PR DESCRIPTION
**Pull request by theimo1221**
*Note*: the `socket.io.js` file is the generated output of `make socket.io.js`, and should not be manually modified.

### The kind of change this PR does introduce

* [x] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Other information (e.g. related issues)

Adding security patch as documented here: https://github.com/socketio/engine.io-client/releases/tag/3.5.2

### CODE REVIEW

**Comment by darrachequesne** [comment]
`~3.5.0` should already included `engine.io-client@3.5.2`. Am I missing something?

**Comment by theimo1221** [comment]
> `~3.5.0` should already included `engine.io-client@3.5.2`. Am I missing something?

This PR is targeting 2.4.x which unfortunately is still in use with some projets.

**Comment by darrachequesne** [comment]
@theimo1221 is this really needed though? Isn't that the role of the version range? I wasn't able to find any documentation about this.

**Comment by theimo1221** [comment]
@darrachequesne Following is from npm doc:
> Allows patch-level changes if a minor version is specified on the comparator. Allows minor-level changes if not.

>~1.2.3 := >=1.2.3 <1.(2+1).0 := >=1.2.3 <1.3.0
~1.2 := >=1.2.0 <1.(2+1).0 := >=1.2.0 <1.3.0 (Same as 1.2.x)

We have to focus on the "allows". As we have a critical security patch here, this should not just be allowed, it should be enforced.

**Comment by theimo1221** [comment]
> socket.io-client@2.4.0 requires xmlhttprequest-ssl@~1.5.4 via engine.io-client@3.5.0

**Comment by theimo1221** [comment]
@darrachequesne As this contains a security hotfix I'd appreciate if we could speed up the process here.

**Comment by darrachequesne** [comment]
Everything seems to be OK though:

```
$ npm i socket.io-client@2

+ socket.io-client@2.4.0
added 24 packages from 19 contributors and audited 24 packages in 1.363s
found 0 vulnerabilities

$ npm ls xmlhttprequest-ssl
└─┬ socket.io-client@2.4.0
  └─┬ engine.io-client@3.5.2
    └── xmlhttprequest-ssl@1.6.2
```

```
$ npm i socket.io-client@3

+ socket.io-client@3.1.3
added 1 package from 1 contributor, removed 9 packages, updated 6 packages and audited 16 packages in 1.098s
found 0 vulnerabilities

$ npm ls xmlhttprequest-ssl
└─┬ socket.io-client@3.1.3
  └─┬ engine.io-client@4.1.4
    └── xmlhttprequest-ssl@1.6.2
```

I don't think that there is much more that we can do. Please reopen if needed.

**Comment by theimo1221** [comment]
@darrachequesne after running npm install (not a fresh folder though) i have this:
image

As installed Version 3.5.0 satisfies the dependency it doesn´t use the newer versions on its own.

Forcing him to fresh install -e.g. by deleting the node_modules folder- it uses the new version:
image

So as said above, please enforce using the patched version.

**Pull request closed without merging**
