### PR TITLE
Support minified `socket.io.min.js`

### PR DESCRIPTION
**Pull request by bananaappletw**
Support the functionality of generating minified `socket.io.min.js`.

### The kind of change this PR does introduce

* [x] a new feature
* [x] an update to the documentation

### Current behaviour

No minified `socket.io.min.js`.

### New behaviour

After running `make socket.io.js`, minified `socket.io.min.js` is generated.

### Other information (e.g. related issues)

None.

### CODE REVIEW

**Comment by bananaappletw** [comment]
Sometimes the test will pass sometimes not.
Seems like timeout is too short for the test.
If the Travis ci's container is in good condition, the test will pass.
Else not.

**Comment by darrachequesne** [comment]
I think it related to the `node` target, which now equals to node v7 (it's not related to the PR).

**Comment by bananaappletw** [comment]
@darrachequesne 
Not exactlly.
Take a look of this one.
https://travis-ci.org/socketio/socket.io-client/builds/174189877
Test failed in Node 0.10

**Comment by bananaappletw** [comment]
@darrachequesne 
I think this test prove it.
It passed!

**Comment by bananaappletw** [comment]
@darrachequesne 
Any update here?

**Comment by darrachequesne** [comment]
@bananaappletw thanks!

**Pull request merged**
