### PR TITLE
socket.io-parser library upgrade from v4.2.0 to v4.2.1

### PR DESCRIPTION
**Pull request by Annniee1**
*Note*: the `socket.io.js` file is the generated output of `make socket.io.js`, and should not be manually modified.

### The kind of change this PR does introduce

* [x] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### CODE REVIEW

**Comment by Annniee1** [comment]
@darrachequesne Please Review this Pull Request

**Comment by Annniee1** [comment]
@rauchg @3rd-Eden @nkzawa @zweihan @kevin-roark Please Review this PR

**Comment by darrachequesne** [comment]
@Annniee1 the version does not exist, could you please check?

**Comment by Annniee1** [comment]
@darrachequesne Hey!  Thanks for this. I got confused between 4.0.5 and 4.5.0 . Btw, Thanks :)

**Comment by Annniee1** [comment]
@darrachequesne Thanks for your quick response. I have Edited my files. Can you please Review it once again

**Comment by Annniee1** [comment]
@darrachequesne Please have a look at the changed files Once.

**Comment by darrachequesne** [comment]
Merged as https://github.com/socketio/socket.io-client/commit/cedd3117cfd49efe43e724b7fbb7c57e3331c8f4. Thanks :+1:

**Comment by vinodkumarsharma276** [comment]
Thanks @darrachequesne for bumping socket.io-client. When can we expect this to published to npm?

**Comment by Annniee1** [comment]
@darrachequesne Are we bumping the version for socket.io-client after this bump of socket.io-parser

**Comment by darrachequesne** [comment]
@vinodkumarsharma276 @Annniee1 `socket.io-client@4.5.3` uses `socket.io-parser@~4.2.0`, so running npm audit fix or npm update socket.io-parser should be sufficient I think.

**Pull request closed without merging**
